[tool.poetry]
name = "tti_contracts"
version = "0.1.0"
description = "Custom-built SDK for TTI lorawan stack"
authors = ["Alexey Zakharov <alexey.zakharov@everynet.com>"]

packages = [
    { include = "tti_contracts" },
]

[tool.poetry.dependencies]
python = "^3.10"
protobuf = "<3.21"

# We don't care about this package versions, because they are hardly depend on "protobuf" version
grpcio = "*" 
grpcio-tools = "*" 
mypy-protobuf = "*"

# main dependencies, because build uses those to autoformat generated files
black = "^22.12.0"
isort = "^5.11.2"

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
include = '\.pyi?$'
target-version = ["py310", "py311"]
preview = true
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pip-cache
  | \.poetry
  | \.venv
  | \.vscode
  | _build
  | buck-out
  | build
  | dist
  | __pycache__
)/
'''

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
